services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.51.0
    container_name: cadvisor
    ports:
 - 9101:8080
    volumes:
 - /:/rootfs:ro
 - /run:/run:ro
 - /sys:/sys:ro
 - /var/lib/docker/:/var/lib/docker:ro
 - /dev/disk/:/dev/disk:ro
    devices:
 - /dev/kmsg
    privileged: true
    restart: unless-stopped
    labels:
 org.label-schema.group: "monitoring"
  promtail:
    image: grafana/promtail:2.9.2
    volumes:
 - /var/log:/var/log
 - ./promtail:/etc/promtail
    # ports:
    #   - "1514:1514" # this is only needed if you are going to send syslogs
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
