version: '3'
services:
  guacd:
#    image: guacamole/guacd:latest
    image: guacamole/guacd:1.5.3
    restart: always
    ports: 
      - 10.250.0.20:4822:4822
    dns:
      - 10.250.0.100
    volumes:
      - ./record:/var/lib/guacamole/recordings
