services:
  node_exporter:
    ports:
      - 9100:9100
    image: quay.io/prometheus/node-exporter:v1.8.2
    container_name: node_exporter
    command: "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
    labels:
      org.label-schema.group: "monitoring"

