server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.250.3.20:3100/loki/api/v1/push

#client:
#  url: http://loki.thekor.eu/loki/api/v1/push
#  basic_auth:
#    username: admin
#    password: superlongpassword
# htpasswd -c /etc/loki/.htpasswd admin superlongpassword twice

scrape_configs:

# local machine logs

- job_name: system
  static_configs:
  - targets:
 - localhost
    labels:
 job: varlogs
 __path__: /var/log/*log

## docker logs

- job_name: docker 
  pipeline_stages:
    - docker: {}
  static_configs:
    - labels:
 job: docker
 __path__: /var/lib/docker/containers/*/*-json.log
